In [41]:
from shapely.geometry import shape,Polygon,MultiPolygon,mapping
import geopandas as gpd
from shapely.validation import make_valid
from osgeo import gdal
from osgeo import ogr
import pandas as pd

In [32]:
g1 = gpd.GeoDataFrame.from_file("gaul2015-2014_adm2.shp")

g2 = gpd.GeoDataFrame.from_file("WA_200907_CS.shp")

In [35]:
combined = gpd.sjoin(g1,g2,how="right",op="intersects")
combined

C:\Users\ASUS\anaconda3\envs\plotlyenv\lib\site-packages\IPython\core\interactiveshell.py:3337: FutureWarning: The `op` parameter is deprecated and will be removed in a future release. Please use the `predicate` parameter instead.
  if await self.run_code(code, result, async_=asy):

,index_left,adm2_code,adm2_name,str2_year,exp2_year,adm1_code,adm1_name,status,disp_area,adm0_code,adm0_name,shape_leng,shape_area,FID,CS,geometry
0,1558,65360.0,Arada,NaN,None,870.0,Biltine,Member State,NO,50.0,Chad,6.133665,1.484626,1558,1,"MULTIPOLYGON (((3.26787 6.70693, 3.27315 6.705..."
0,1559,65415.0,Bol,NaN,None,875.0,Lac,Member State,NO,50.0,Chad,5.034863,1.375865,1559,1,"MULTIPOLYGON (((3.26787 6.70693, 3.27315 6.705..."
0,1563,65579.0,Massakory,NaN,None,12912.0,Hadjer Lamis,Member State,NO,50.0,Chad,4.319417,0.700964,1563,1,"MULTIPOLYGON (((3.26787 6.70693, 3.27315 6.705..."
0,1564,65636.0,Ngouri,NaN,None,12915.0,Kanem,Member State,NO,50.0,Chad,2.781632,0.281735,1564,1,"MULTIPOLYGON (((3.26787 6.70693, 3.27315 6.705..."
0,1567,65353.0,Abou-charib-ii,2000.0,None,870.0,Biltine,Member State,NO,50.0,Chad,0.962522,0.062866,1567,1,"MULTIPOLYGON (((3.26787 6.70693, 3.27315 6.705..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2,5651,19532.0,Ouad Naga,NaN,None,2016.0,Trarza,Member State,NO,159.0,Mauritania,7.228430,1.850691,5927,3,"MULTIPOLYGON (((15.00289 10.00131, 15.00600 10..."
2,5657,19375.0,Menaka,NaN,None,1927.0,Gao,Member State,NO,155.0,Mali,11.383892,6.533067,5933,3,"MULTIPOLYGON (((15.00289 10.00131, 15.00600 10..."
2,5668,19386.0,Tin-Essako,NaN,None,1929.0,Kidal,Member State,NO,155.0,Mali,6.871093,2.319554,5944,3,"MULTIPOLYGON (((15.00289 10.00131, 15.00600 10..."
2,5686,19405.0,Niono,NaN,None,1932.0,Segou,Member State,NO,155.0,Mali,5.838367,1.348692,5962,3,"MULTIPOLYGON (((15.00289 10.00131, 15.00600 10..."
2,5698,19417.0,Goundam,NaN,None,1934.0,Tombouctou,Member State,NO,155.0,Mali,19.268662,9.787502,5974,3,"MULTIPOLYGON (((15.00289 10.00131, 15.00600 10..."

In [39]:
df = gpd.GeoDataFrame(combined, geometry='geometry')
#df.to_file(r'C:\Users\ASUS\Desktop\testi\gaul\my_shapefile.shp')